### ISSUE TITLE
Need a function to check if an exception has been raised

### ISSUE THREAD

**Issue by remileduc** [mrzechonek/tut-framework#13]
It would be nice to have a function like `ensure_throw` that asserts that an error has been thrown.

If you are interested, I can try to make one.

**Comment by mrzechonek** [comment]
See https://github.com/mrzechonek/tut-framework/blob/master/include/tut/tut_macros.hpp

**Comment by remileduc** [comment]
sorry I missed it :(

**Comment by mrzechonek** [comment]
No worries, the docs aren't the best :)
