### ISSUE TITLE
Why use global include ?

### ISSUE THREAD

**Issue by lifeisdream** [mrzechonek/tut-framework#14]
Hi, thanks for the library, but I have one question when I try to integrate it into android java \ cpp app, I can't build it with cmake by default, because of  some global includes inside the library:
`#include <tut/tut_config.hpp>` for example.

Yes, I fixed this by specifying cmake work with such <> includes inside library module, but whether or not there is some background about such include style? 

thanks in advance,

**Comment by mrzechonek** [comment]
Well, it's the usual style found in libraries - tut is meant to be installed somewhere.
